# Generated by Django 4.0.4 on 2022-05-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='password',
        ),
    ]
