# Generated by Django 4.0.4 on 2022-05-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userlogin_password_userregister_confirm_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
