# Generated by Django 4.0.4 on 2022-05-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
