# Generated by Django 4.0.4 on 2022-05-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_post_date_posted_post_body_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default=None, max_length=250),
        ),
    ]
