# Generated by Django 4.0.4 on 2022-05-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_post_author_post_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
