# Generated by Django 4.0.4 on 2022-05-25 12:29

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_post_likes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
