# Generated by Django 4.0.4 on 2022-05-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
