# Generated by Django 4.0.4 on 2022-05-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
