# Generated by Django 4.0.4 on 2022-08-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_comment_email_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_good',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
